[package]
name = "luau-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"], optional = true }
smol_str = "0.3.2"

[features]
serde = ["dep:serde","smol_str/serde"]
